pipeline:
  name: sas-pipeline-library
  branch: delevop

default:
  git:
    url: https://umane.emeal.nttdata.com/git/SWFPRESUNISWFPRESCRI/presunmwc/gwpresclgcypducomside-msc.git
    # credentialsId: git-ssh-otro   # opcional
  type: MAVEN
  agent: maven
  stages:
    build: 
      enable: true
      jdk: "JDK21"
      mavenVersion: "maven3.9.11"
      command: "clean install"
    sonar:
      enable: true
      container: "jdk21-mvn-sas201"
    artifact: 
      enable: true
      docker:
        dockerBuild:
          additionalParams:
            - "--build-arg SERVER_XML_PATH=gwpresclgcypducomside-boot/src/main/liberty/config/"
            - "--build-arg WAR_PATH=gwpresclgcypducomside-boot/target/gwpresclgcypducomside.war"

integration:
  stages:
    deploy: 
      enable: false
      env: "integration"
      namespace: "pdu-integration"         # override para integration

certification:
  stages:
    deploy: 
      enable: false
      env: "certification"
      namespace: "pdu-certification"        # override para certification
